### ISSUE TITLE
Clarify demo usage

### ISSUE THREAD

**Issue by BastianZim** [serverless/aws-ai-stack#6]
This is a super cool tool! Thank you!

Just one question regarding the demo. Can we just sign up and test it or how does that work? Not sure if there are any cost incurred etc.

Thanks! :)

**Comment by skierkowski** [comment]
@BastianZim Thanks! Yeah, there are two ways to use the demo. The easiest is just to go to [awsaistack.com](https://awsaistack.com), which is a live instance of this project. The second is to clone the repo and follow the "Getting Started" steps, which guides you through getting your own instance of the app (just like awsaistack.com), but on your own AWS account.

**Comment by BastianZim** [comment]
Ahh perfect! Wasn't sure if we can just use the website. Thanks!
